-- JoyLab Content Registry V1.5 → Content OS V1.6 seed
insert into public.contents
(content_id, title, url, hub, pillar, series, content_type, priority, status, category, published_at)
values
('JL-SEM-001', '삼성전자 주가 전망 2026｜HBM4·2nm·AI 반도체 총정리', 'https://blog.naver.com/joy014/224394211662', '반도체', '삼성전자 투자지도', '삼성전자 재평가', 'Pillar', 'P1', 'UPDATE', '투자·반도체', NULL),
('JL-SEM-002', '삼성전자 HBM4가 중요한 진짜 이유', 'https://blog.naver.com/joy014/224394222150', '반도체', '삼성전자 투자지도', '삼성전자 재평가', 'Search', 'P1', 'NEW', '투자·반도체', NULL),
('JL-SEM-003', '삼성전자 2nm GAA가 파운드리 반전을 만들 수 있을까', 'https://blog.naver.com/joy014/224394231888', '반도체', '삼성전자 투자지도', '삼성전자 재평가', 'Search', 'P1', 'NEW', '투자·반도체', NULL),
('JL-SEM-004', '삼성전자 주주환원 정책 총정리｜배당·FCF·투자자가 볼 것', 'https://blog.naver.com/joy014/224386398320', '반도체', '삼성전자 투자지도', '삼성전자 재평가', 'Search', 'P1', 'UPDATE', '투자·반도체', NULL),
('JL-SEM-005', 'SK하이닉스 주가 전망 2026｜HBM4·AI 메모리·eSSD', 'https://blog.naver.com/joy014/224394237129', '반도체', 'SK하이닉스 투자지도', 'HBM 리더십', 'Pillar', 'P1', 'UPDATE', '투자·반도체', NULL),
('JL-SEM-006', 'HBM4란 무엇인가｜HBM3E와 무엇이 달라졌나', 'https://blog.naver.com/joy014/224394223035', '반도체', 'SK하이닉스 투자지도', 'HBM 리더십', 'Evergreen', 'P1', 'NEW', '투자·반도체', NULL),
('JL-SEM-007', '엔비디아 실적이 SK하이닉스 주가에 미치는 영향', NULL, '반도체', 'SK하이닉스 투자지도', 'HBM 리더십', 'Traffic', 'P1', 'UPDATE', '투자·반도체', NULL),
('JL-SEM-008', 'SK하이닉스 NAND·eSSD가 다시 중요해지는 이유', NULL, '반도체', 'SK하이닉스 투자지도', 'HBM 리더십', 'Search', 'P2', 'NEW', '투자·반도체', NULL),
('JL-SEM-009', '필라델피아 반도체지수 급락 원인 총정리', NULL, '반도체', '반도체 사이클', '반도체 급락 대응', 'Traffic', 'P1', 'EXISTING', '투자·반도체', NULL),
('JL-SEM-010', '미국 금리가 삼성전자·SK하이닉스에 미치는 영향', NULL, '반도체', '반도체 사이클', '반도체 급락 대응', 'Search', 'P1', 'UPDATE', '투자·반도체', NULL),
('JL-SEM-011', '반도체 급락장에서 사야 할 것과 기다려야 할 것', NULL, '반도체', '반도체 사이클', '반도체 급락 대응', 'Traffic', 'P1', 'EXISTING', '투자·반도체', NULL),
('JL-SEM-012', '메모리 반도체 사이클은 어떻게 읽어야 하나', NULL, '반도체', '반도체 사이클', '반도체 급락 대응', 'Evergreen', 'P1', 'NEW', '투자·반도체', NULL),
('JL-AI-013', 'AI CAPEX란 무엇인가｜투자자가 반드시 알아야 할 이유', 'https://blog.naver.com/joy014/224394224885', 'AI CAPEX', 'AI CAPEX 투자지도', 'AI 돈의 이동', 'Pillar', 'P1', 'UPDATE', 'AI·인프라', NULL),
('JL-AI-014', 'AI 투자금은 왜 GPU에서 인프라 전체로 확산되는가', NULL, 'AI CAPEX', 'AI CAPEX 투자지도', 'AI 돈의 이동', 'Authority', 'P1', 'UPDATE', 'AI·인프라', NULL),
('JL-AI-015', '빅테크 AI CAPEX 증가는 어디까지 지속될까', NULL, 'AI CAPEX', 'AI CAPEX 투자지도', 'AI 돈의 이동', 'Search', 'P2', 'NEW', 'AI·인프라', NULL),
('JL-AI-016', 'AI CAPEX를 주식투자에 연결하는 5단계', NULL, 'AI CAPEX', 'AI CAPEX 투자지도', 'AI 돈의 이동', 'Authority', 'P1', 'NEW', 'AI·인프라', NULL),
('JL-AI-017', 'AI 데이터센터가 전력 부족을 만드는 이유', NULL, 'AI CAPEX', 'AI 데이터센터', '데이터센터 병목', 'Search', 'P1', 'UPDATE', 'AI·인프라', NULL),
('JL-AI-018', 'GPU보다 먼저 부족해질 수 있는 전력·냉각·변압기', NULL, 'AI CAPEX', 'AI 데이터센터', '데이터센터 병목', 'Search', 'P2', 'UPDATE', 'AI·인프라', NULL),
('JL-AI-019', 'AI 데이터센터가 기업용 SSD를 다시 키우는 이유', NULL, 'AI CAPEX', 'AI 데이터센터', '데이터센터 병목', 'Search', 'P1', 'UPDATE', 'AI·인프라', NULL),
('JL-AI-020', '키옥시아 대규모 NAND 투자를 어떻게 봐야 하나', NULL, 'AI CAPEX', 'AI 데이터센터', '데이터센터 병목', 'Traffic', 'P2', 'EXISTING', 'AI·인프라', '2026-08-29'),
('JL-AI-021', 'GPU 다음은 전력인가｜AI Power 투자지도', NULL, 'AI CAPEX', 'AI Power', 'GPU 다음 투자처', 'Authority', 'P1', 'UPDATE', 'AI·인프라', NULL),
('JL-AI-022', 'AI 전력인프라 ETF 5종 비교', NULL, 'AI CAPEX', 'AI Power', 'GPU 다음 투자처', 'Search', 'P1', 'NEW', 'AI·인프라', NULL),
('JL-AI-023', 'LS ELECTRIC이 AI 데이터센터 수혜주로 거론되는 이유', NULL, 'AI CAPEX', 'AI Power', 'GPU 다음 투자처', 'Investment', 'P1', 'NEW', 'AI·인프라', NULL),
('JL-AI-024', 'AI 전력 투자에서 발전·송전·변압·배전을 구분해야 하는 이유', NULL, 'AI CAPEX', 'AI Power', 'GPU 다음 투자처', 'Evergreen', 'P2', 'NEW', 'AI·인프라', NULL),
('JL-ETF-025', 'KODEX200 완전정리｜구성종목·보수·장단점', NULL, 'ETF·시장', 'KODEX200 투자지도', 'ETF 기본기', 'Pillar', 'P1', 'EXISTING', '투자·시장', NULL),
('JL-ETF-026', 'KODEX200에서 삼성전자·SK하이닉스 비중이 중요한 이유', NULL, 'ETF·시장', 'KODEX200 투자지도', 'ETF 기본기', 'Search', 'P1', 'UPDATE', '투자·시장', NULL),
('JL-ETF-027', 'KODEX200 vs TIGER200 무엇이 다를까', NULL, 'ETF·시장', 'KODEX200 투자지도', 'ETF 기본기', 'Search', 'P2', 'NEW', '투자·시장', NULL),
('JL-ETF-028', '삼성전자 개별주와 KODEX200 중 무엇을 살까', NULL, 'ETF·시장', 'KODEX200 투자지도', 'ETF 기본기', 'Search', 'P2', 'NEW', '투자·시장', NULL),
('JL-MKT-029', '미국 금리와 한국 주식의 관계', NULL, 'ETF·시장', '시장환경', '금리·환율·수급', 'Evergreen', 'P2', 'UPDATE', '투자·시장', NULL),
('JL-MKT-030', '원달러 환율 상승이 삼성전자에 미치는 영향', NULL, 'ETF·시장', '시장환경', '금리·환율·수급', 'Search', 'P2', 'NEW', '투자·시장', NULL),
('JL-MKT-031', '외국인 순매수·순매도는 어떻게 읽어야 하나', NULL, 'ETF·시장', '시장환경', '금리·환율·수급', 'Evergreen', 'P2', 'UPDATE', '투자·시장', NULL),
('JL-MKT-032', '코스피 급락장에서 확인해야 할 5가지', NULL, 'ETF·시장', '시장환경', '금리·환율·수급', 'Search', 'P2', 'UPDATE', '투자·시장', NULL),
('JL-FIN-033', 'KB금융 주가 전망｜ROE·CET1·주주환원으로 보는 법', NULL, '금융', '금융·배당', '금융주 투자법', 'Investment', 'P3', 'EXISTING', '투자·금융', NULL),
('JL-FIN-034', '은행주는 PER보다 PBR을 봐야 하는 이유', NULL, '금융', '금융·배당', '금융주 투자법', 'Evergreen', 'P3', 'NEW', '투자·금융', NULL),
('JL-FIN-035', 'CET1이란 무엇인가', NULL, '금융', '금융·배당', '금융주 투자법', 'Evergreen', 'P3', 'NEW', '투자·금융', NULL),
('JL-FIN-036', '증권사 실적이 좋아도 주가가 떨어지는 이유', NULL, '금융', '금융·배당', '금융주 투자법', 'Traffic', 'P3', 'EXISTING', '투자·금융', '2026-08-29'),
('JL-ENG-037', 'AI가 코딩하는 시대에 코드를 더 알아야 하는 이유', NULL, 'AI Engineering', 'AI Agent 시대', 'Agent Engineering', 'Authority', 'P3', 'EXISTING', 'AI·업무자동화', NULL),
('JL-ENG-038', 'Agent Engineering이 Prompt Engineering과 다른 점', NULL, 'AI Engineering', 'AI Agent 시대', 'Agent Engineering', 'Evergreen', 'P3', 'UPDATE', 'AI·업무자동화', NULL),
('JL-ENG-039', 'AI Agent의 Self-Recovery란 무엇인가', NULL, 'AI Engineering', 'AI Agent 시대', 'Agent Engineering', 'Search', 'P2', 'EXISTING', 'AI·업무자동화', '2026-08-29'),
('JL-ENG-040', '작은 AI가 경험으로 성장하는 WikiSkill', NULL, 'AI Engineering', 'AI Agent 시대', 'Agent Engineering', 'Search', 'P3', 'EXISTING', 'AI·업무자동화', NULL),
('JL-WRK-041', 'ChatGPT로 업무자동화할 때 먼저 설계해야 할 것', NULL, 'AI Engineering', 'AI 업무자동화', '직장인의 AI', 'Evergreen', 'P3', 'NEW', 'AI·업무자동화', NULL),
('JL-WRK-042', 'Claude Code와 Codex를 어떻게 구분해 쓸까', NULL, 'AI Engineering', 'AI 업무자동화', '직장인의 AI', 'Search', 'P3', 'NEW', 'AI·업무자동화', NULL),
('JL-WRK-043', '비개발자가 AI로 앱을 만들 때 가장 많이 실패하는 이유', NULL, 'AI Engineering', 'AI 업무자동화', '직장인의 AI', 'Authority', 'P3', 'UPDATE', 'AI·업무자동화', NULL),
('JL-WRK-044', 'AI에게 ‘코드 짜줘’라고 하면 안 되는 이유', NULL, 'AI Engineering', 'AI 업무자동화', '직장인의 AI', 'Traffic', 'P3', 'UPDATE', 'AI·업무자동화', NULL),
('JL-BLD-045', '비개발자가 Investment OS를 만든 과정', NULL, 'JoyLab Build', 'JoyLab Build Log', 'AI로 실제 제품 만들기', 'Brand', 'P3', 'UPDATE', 'JoyLab Build', NULL),
('JL-BLD-046', 'AI 투자판단을 사자·보류·팔자로 단순화한 이유', NULL, 'JoyLab Build', 'JoyLab Build Log', 'AI로 실제 제품 만들기', 'Brand', 'P3', 'NEW', 'JoyLab Build', NULL),
('JL-BLD-047', '영상 하나를 Shorts 3개로 만드는 AI 엔진 설계', NULL, 'JoyLab Build', 'JoyLab Build Log', 'AI로 실제 제품 만들기', 'Brand', 'P3', 'UPDATE', 'JoyLab Build', NULL),
('JL-BLD-048', '상담사 교육용 AI Question Engine을 만드는 방법', NULL, 'JoyLab Build', 'JoyLab Build Log', 'AI로 실제 제품 만들기', 'Brand', 'P3', 'UPDATE', 'JoyLab Build', NULL),
('JL-BLD-049', '오픈AI, 스페이스X 인수 Cursor 모델 공급 종료 예고｜AI 코딩 도구 ‘단일 모델 의존’ 리스크가 커진 이유', 'https://blog.naver.com/joy014/224394788584', 'AI Engineering', 'AI 코딩 생태계', '모델 공급 리스크', 'Traffic', 'P2', 'EXISTING', 'AI·업무자동화', '2026-08-30'),
('JL-BLD-050', '중국 AI 반도체 비런 테크놀로지 매출 20배 급증｜국산 AI 가속기 상용화가 빨라지는 이유', 'https://blog.naver.com/joy014/224394790348', '반도체', '중국 AI 반도체', 'AI 가속기 자립', 'Traffic', 'P2', 'EXISTING', '투자·반도체', '2026-08-30'),
('JL-BLD-051', '코스피 6,788.88 주간 -1.79%…연준 매파 발언 이후 다음 주 방향성 좌우할 3가지 변수', 'https://blog.naver.com/joy014/224394797176', 'ETF·시장', '시장환경', '주간 시장전망', 'Traffic', 'P1', 'EXISTING', '투자·시장', '2026-08-30'),
('JL-BLD-052', 'IIF 원화 강세 전망｜반도체 수출 호조가 원·달러 환율을 끌어내리는 이유', 'https://blog.naver.com/joy014/224394799161', 'ETF·시장', '시장환경', '환율·수출', 'Traffic', 'P2', 'EXISTING', '투자·시장', '2026-08-30'),
('JL-BLD-053', '단일종목 레버리지 규제 한 달｜개미 1.77조 순매도, 삼성전자·SK하이닉스 수급은 어디로 갔나', 'https://blog.naver.com/joy014/224394800905', 'ETF·시장', '시장제도', '레버리지 규제', 'Traffic', 'P2', 'EXISTING', '투자·시장', '2026-08-30'),
('JL-BLD-054', '한국 AI 활용 글로벌 평균 1.7배…업무 자동화보다 더 중요한 ‘AI 활용 역량’', 'https://blog.naver.com/joy014/224394804055', 'AI Engineering', 'AI 업무자동화', '직장인의 AI', 'Authority', 'P2', 'EXISTING', 'AI·업무자동화', '2026-08-30'),
('JL-BLD-055', '관악구 AI 행정 혁신 플랫폼 가동｜공무원이 직접 만든 ‘관악 AI 마당’이 바꾸는 행정업무', 'https://blog.naver.com/joy014/224394806236', 'AI Engineering', '공공 AI', 'AI 행정 혁신', 'Traffic', 'P3', 'EXISTING', 'AI·업무자동화', '2026-08-30'),
('JL-BLD-056', '삼성전자·SK하이닉스 자사주 10조 매수｜기타법인이 코스피 수급 방파제로 떠오른 이유', 'https://blog.naver.com/joy014/224394808473', '반도체', '반도체 수급', '자사주·기타법인', 'Traffic', 'P1', 'EXISTING', '투자·반도체', '2026-08-30'),
('JL-BLD-057', '삼성전기 유리기판 로드맵 공개｜AI 반도체 패키징 시장에서 주목받는 이유', 'https://blog.naver.com/joy014/224394811604', '반도체', '첨단 패키징', '유리기판', 'Traffic', 'P1', 'EXISTING', '투자·반도체', '2026-08-30'),
('JL-BLD-058', '잭슨홀 이후 뉴욕 증시 주간 상승｜VOO $707 지지력과 9월 FOMC 핵심 변수', 'https://blog.naver.com/joy014/224394828327', 'ETF·시장', '미국 ETF', 'S&P500·VOO', 'Investment', 'P1', 'EXISTING', '투자·시장', '2026-08-30'),
('JL-BLD-059', '2026 멀티 에이전트 AI 트렌드｜기업 업무 자동화가 ‘챗봇’에서 ‘업무 완수’로 바뀌는 이유', 'https://blog.naver.com/joy014/224394829637', 'AI Engineering', 'AI Agent 시대', 'Multi-Agent', 'Authority', 'P1', 'EXISTING', 'AI·업무자동화', '2026-08-30'),
('JL-BLD-060', '지상 전력망 병목이 ‘우주 데이터센터’를 부르는 이유｜Orbital AIDC 현실성과 투자 시사점', NULL, 'AI CAPEX', 'AI 데이터센터', '우주 데이터센터', 'Traffic', 'P2', 'NEW', 'AI·인프라', NULL),
('JL-BLD-061', '하드웨어의 한국·소프트웨어의 실리콘밸리｜AI-반도체 넥서스 동맹이 필요한 이유', NULL, 'AI CAPEX', 'AI-반도체 생태계', '한미 AI 동맹', 'Authority', 'P2', 'NEW', 'AI·인프라', NULL),
('JL-BLD-062', '미국 반도체 관세, AI 서버까지 번질까｜한국 기업 공급망 영향과 대응 시나리오', NULL, '반도체', '글로벌 공급망', '미국 반도체 관세', 'Traffic', 'P1', 'NEW', '투자·반도체', NULL)
on conflict (content_id) do update set
  title = excluded.title,
  url = coalesce(excluded.url, public.contents.url),
  hub = excluded.hub,
  pillar = excluded.pillar,
  series = excluded.series,
  content_type = excluded.content_type,
  priority = excluded.priority,
  status = excluded.status,
  category = excluded.category,
  published_at = coalesce(excluded.published_at, public.contents.published_at),
  updated_at = now();

insert into public.keywords
(content_id, primary_keyword, keyword_group, aliases, enabled)
values
('JL-SEM-001', '삼성전자 전망', '삼성전자 전망', '[]'::jsonb, true),
('JL-SEM-002', '삼성전자 HBM4', '삼성전자 HBM4', '[]'::jsonb, true),
('JL-SEM-003', '삼성전자 2nm', '삼성전자 2nm', '[]'::jsonb, true),
('JL-SEM-004', '삼성전자 주주환원', '삼성전자 주주환원', '[]'::jsonb, true),
('JL-SEM-005', 'SK하이닉스 전망', 'SK하이닉스 전망', '[]'::jsonb, true),
('JL-SEM-006', 'HBM4란', 'HBM4란', '[]'::jsonb, true),
('JL-SEM-007', '엔비디아 SK하이닉스', '엔비디아 SK하이닉스', '[]'::jsonb, true),
('JL-SEM-008', 'SK하이닉스 eSSD', 'SK하이닉스 eSSD', '[]'::jsonb, true),
('JL-SEM-009', '필라델피아 반도체지수', '필라델피아 반도체지수', '[]'::jsonb, true),
('JL-SEM-010', '미국 금리 반도체', '미국 금리 반도체', '[]'::jsonb, true),
('JL-SEM-011', '반도체 급락 투자', '반도체 급락 투자', '[]'::jsonb, true),
('JL-SEM-012', '메모리 반도체 사이클', '메모리 반도체 사이클', '[]'::jsonb, true),
('JL-AI-013', 'AI CAPEX', 'AI CAPEX', '[]'::jsonb, true),
('JL-AI-014', 'AI 인프라 투자', 'AI 인프라 투자', '[]'::jsonb, true),
('JL-AI-015', '빅테크 AI CAPEX', '빅테크 AI CAPEX', '[]'::jsonb, true),
('JL-AI-016', 'AI CAPEX 투자전략', 'AI CAPEX 투자전략', '[]'::jsonb, true),
('JL-AI-017', 'AI 데이터센터 전력', 'AI 데이터센터 전력', '[]'::jsonb, true),
('JL-AI-018', 'AI 데이터센터 병목', 'AI 데이터센터 병목', '[]'::jsonb, true),
('JL-AI-019', '기업용 SSD AI', '기업용 SSD AI', '[]'::jsonb, true),
('JL-AI-020', '키옥시아 NAND 투자', '키옥시아 NAND 투자', '[]'::jsonb, true),
('JL-AI-021', 'AI 전력 투자', 'AI 전력 투자', '[]'::jsonb, true),
('JL-AI-022', 'AI 전력 ETF', 'AI 전력 ETF', '[]'::jsonb, true),
('JL-AI-023', 'LS ELECTRIC AI', 'LS ELECTRIC AI', '[]'::jsonb, true),
('JL-AI-024', 'AI 전력 밸류체인', 'AI 전력 밸류체인', '[]'::jsonb, true),
('JL-ETF-025', 'KODEX200', 'KODEX200', '[]'::jsonb, true),
('JL-ETF-026', 'KODEX200 삼성전자 비중', 'KODEX200 삼성전자 비중', '[]'::jsonb, true),
('JL-ETF-027', 'KODEX200 TIGER200', 'KODEX200 TIGER200', '[]'::jsonb, true),
('JL-ETF-028', '삼성전자 KODEX200', '삼성전자 KODEX200', '[]'::jsonb, true),
('JL-MKT-029', '미국 금리 한국주식', '미국 금리 한국주식', '[]'::jsonb, true),
('JL-MKT-030', '환율 삼성전자', '환율 삼성전자', '[]'::jsonb, true),
('JL-MKT-031', '외국인 수급', '외국인 수급', '[]'::jsonb, true),
('JL-MKT-032', '코스피 급락', '코스피 급락', '[]'::jsonb, true),
('JL-FIN-033', 'KB금융 전망', 'KB금융 전망', '[]'::jsonb, true),
('JL-FIN-034', '은행주 PBR', '은행주 PBR', '[]'::jsonb, true),
('JL-FIN-035', 'CET1', 'CET1', '[]'::jsonb, true),
('JL-FIN-036', '증권사 피크아웃', '증권사 피크아웃', '[]'::jsonb, true),
('JL-ENG-037', 'AI 코딩 시대', 'AI 코딩 시대', '[]'::jsonb, true),
('JL-ENG-038', 'Agent Engineering', 'Agent Engineering', '[]'::jsonb, true),
('JL-ENG-039', 'AI Self-Recovery', 'AI Self-Recovery', '[]'::jsonb, true),
('JL-ENG-040', 'WikiSkill', 'WikiSkill', '[]'::jsonb, true),
('JL-WRK-041', 'ChatGPT 업무자동화', 'ChatGPT 업무자동화', '[]'::jsonb, true),
('JL-WRK-042', 'Claude Code Codex', 'Claude Code Codex', '[]'::jsonb, true),
('JL-WRK-043', '비개발자 AI 앱', '비개발자 AI 앱', '[]'::jsonb, true),
('JL-WRK-044', 'AI 코딩 프롬프트', 'AI 코딩 프롬프트', '[]'::jsonb, true),
('JL-BLD-045', 'Investment OS 만들기', 'Investment OS 만들기', '[]'::jsonb, true),
('JL-BLD-046', '사자 보류 팔자', '사자 보류 팔자', '[]'::jsonb, true),
('JL-BLD-047', 'AI Shorts 자동화', 'AI Shorts 자동화', '[]'::jsonb, true),
('JL-BLD-048', 'AI Question Engine', 'AI Question Engine', '[]'::jsonb, true),
('JL-BLD-049', '오픈AI Cursor 계약 종료', '오픈AI Cursor 계약 종료', '[]'::jsonb, true),
('JL-BLD-050', '비런 테크놀로지', '비런 테크놀로지', '[]'::jsonb, true),
('JL-BLD-051', '코스피 주간 전망', '코스피 주간 전망', '[]'::jsonb, true),
('JL-BLD-052', '원화 강세 전망', '원화 강세 전망', '[]'::jsonb, true),
('JL-BLD-053', '단일종목 레버리지 규제', '단일종목 레버리지 규제', '[]'::jsonb, true),
('JL-BLD-054', '한국 AI 활용 수준', '한국 AI 활용 수준', '[]'::jsonb, true),
('JL-BLD-055', 'AI 행정 혁신 플랫폼', 'AI 행정 혁신 플랫폼', '[]'::jsonb, true),
('JL-BLD-056', '삼성전자 SK하이닉스 자사주 매입', '삼성전자 SK하이닉스 자사주 매입', '[]'::jsonb, true),
('JL-BLD-057', '삼성전기 유리기판', '삼성전기 유리기판', '[]'::jsonb, true),
('JL-BLD-058', 'VOO 전망', 'VOO 전망', '[]'::jsonb, true),
('JL-BLD-059', '멀티 에이전트 AI', '멀티 에이전트 AI', '[]'::jsonb, true),
('JL-BLD-060', '우주 데이터센터', '우주 데이터센터', '[]'::jsonb, true),
('JL-BLD-061', '한미 AI 반도체 동맹', '한미 AI 반도체 동맹', '[]'::jsonb, true),
('JL-BLD-062', '미국 반도체 관세 AI 서버', '미국 반도체 관세 AI 서버', '[]'::jsonb, true)
on conflict (content_id, primary_keyword) do update set
  keyword_group = excluded.keyword_group,
  enabled = excluded.enabled;
