-- JoyLab Content OS V1.6 — Database Foundation
create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger language plpgsql set search_path = public as $$
begin new.updated_at = now(); return new; end;
$$;

create table if not exists public.contents (
  id uuid primary key default gen_random_uuid(),
  content_id text not null unique,
  title text not null,
  url text,
  hub text,
  pillar text,
  series text,
  content_type text,
  priority text,
  status text,
  category text,
  published_at timestamptz,
  estimated_effort_hours numeric(8,2),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists contents_status_priority_idx on public.contents(status, priority);
create index if not exists contents_hub_type_idx on public.contents(hub, content_type);
drop trigger if exists trg_contents_updated_at on public.contents;
create trigger trg_contents_updated_at before update on public.contents
for each row execute function public.set_updated_at();

create table if not exists public.keywords (
  id uuid primary key default gen_random_uuid(),
  content_id text not null references public.contents(content_id) on delete cascade,
  primary_keyword text not null,
  keyword_group text not null,
  aliases jsonb not null default '[]'::jsonb,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  unique(content_id, primary_keyword)
);
create index if not exists keywords_enabled_idx on public.keywords(enabled);

create table if not exists public.naver_trend_snapshots (
  id bigint generated by default as identity primary key,
  keyword_id uuid not null references public.keywords(id) on delete cascade,
  period_date date not null,
  ratio numeric(10,4) not null check (ratio >= 0),
  time_unit text not null,
  device text,
  gender text,
  ages jsonb,
  collected_at timestamptz not null default now(),
  source_version text not null default 'naver-api-hub-v1',
  unique(keyword_id, period_date, time_unit, device, gender)
);
create index if not exists naver_trend_keyword_date_idx
  on public.naver_trend_snapshots(keyword_id, period_date desc);

create table if not exists public.search_demand_features (
  id bigint generated by default as identity primary key,
  keyword_id uuid not null references public.keywords(id) on delete cascade,
  as_of_date date not null,
  avg_7d numeric(12,4),
  avg_prev_7d numeric(12,4),
  avg_30d numeric(12,4),
  avg_prev_30d numeric(12,4),
  momentum_7d numeric(12,6),
  momentum_30d numeric(12,6),
  acceleration numeric(12,6),
  volatility_30d numeric(12,6),
  search_demand_score numeric(6,2) not null check (search_demand_score between 0 and 100),
  demand_state text not null check (demand_state in ('BREAKOUT','RISING','STABLE','COOLING','WEAK')),
  created_at timestamptz not null default now(),
  unique(keyword_id, as_of_date)
);
create index if not exists search_demand_score_idx
  on public.search_demand_features(as_of_date desc, search_demand_score desc);

create table if not exists public.gsc_performance_snapshots (
  id bigint generated by default as identity primary key,
  content_id text references public.contents(content_id) on delete cascade,
  page_url text not null,
  query text,
  performance_date date not null,
  clicks numeric(12,2) not null default 0 check (clicks >= 0),
  impressions numeric(12,2) not null default 0 check (impressions >= 0),
  ctr numeric(10,6) not null default 0 check (ctr between 0 and 1),
  position numeric(10,4),
  device text,
  country text,
  collected_at timestamptz not null default now()
);
create index if not exists gsc_content_date_idx
  on public.gsc_performance_snapshots(content_id, performance_date desc);

create table if not exists public.content_score_snapshots (
  id bigint generated by default as identity primary key,
  content_id text not null references public.contents(content_id) on delete cascade,
  as_of_date date not null,
  search_demand_score numeric(6,2),
  actual_search_score numeric(6,2),
  opportunity_score numeric(6,2),
  roi_score numeric(6,2),
  internal_link_score numeric(6,2),
  urgency_score numeric(6,2),
  executive_score numeric(6,2),
  recommended_action text,
  estimated_effort_hours numeric(8,2),
  predicted_30d_traffic numeric(14,2),
  scoring_version text not null,
  created_at timestamptz not null default now(),
  unique(content_id, as_of_date, scoring_version)
);
create index if not exists content_scores_exec_idx
  on public.content_score_snapshots(as_of_date desc, executive_score desc);

create table if not exists public.performance_reviews (
  id bigint generated by default as identity primary key,
  content_id text not null references public.contents(content_id) on delete cascade,
  published_at timestamptz,
  predicted_30d_traffic numeric(14,2),
  actual_clicks_7d numeric(14,2),
  actual_impressions_7d numeric(14,2),
  actual_ctr_7d numeric(10,6),
  actual_clicks_30d numeric(14,2),
  actual_impressions_30d numeric(14,2),
  actual_ctr_30d numeric(10,6),
  accuracy_7d numeric(8,4),
  accuracy_30d numeric(8,4),
  prediction_grade text check (prediction_grade is null or prediction_grade in ('HIT','PARTIAL','MISS')),
  growth_index numeric(10,4),
  review_state text not null default 'WAIT_7D'
    check (review_state in ('WAIT_7D','7D_READY','WAIT_30D','30D_DUE','COMPLETE')),
  updated_at timestamptz not null default now()
);
create index if not exists performance_reviews_state_idx
  on public.performance_reviews(review_state, updated_at desc);

create table if not exists public.executive_actions (
  id bigint generated by default as identity primary key,
  action_date date not null,
  content_id text not null references public.contents(content_id) on delete cascade,
  action_type text not null,
  executive_score numeric(6,2) not null,
  roi_score numeric(6,2),
  opportunity_score numeric(6,2),
  search_demand_score numeric(6,2),
  estimated_effort_hours numeric(8,2),
  queue_rank integer,
  selected boolean not null default false,
  completed boolean not null default false,
  completed_at timestamptz,
  reason text,
  scoring_version text not null,
  created_at timestamptz not null default now()
);
create index if not exists executive_actions_queue_idx
  on public.executive_actions(action_date desc, queue_rank);

create table if not exists public.winner_patterns (
  id bigint generated by default as identity primary key,
  pattern_key text not null unique,
  hub text,
  content_type text,
  keyword_class text,
  sample_count integer not null default 0,
  completed_30d_count integer not null default 0,
  avg_clicks_30d numeric(14,2),
  avg_ctr_30d numeric(10,6),
  hit_rate numeric(10,6),
  avg_growth_index numeric(10,4),
  pattern_state text not null default 'INSUFFICIENT'
    check (pattern_state in ('INSUFFICIENT','WATCH','CERTIFY_CANDIDATE','NO_EDGE')),
  updated_at timestamptz not null default now()
);

create table if not exists public.weight_certifications (
  id bigint generated by default as identity primary key,
  weight_name text not null,
  current_weight numeric(10,4) not null,
  proposed_weight numeric(10,4) not null,
  sample_count integer,
  baseline_accuracy numeric(10,6),
  candidate_accuracy numeric(10,6),
  improvement numeric(10,6),
  backtest_state text not null default 'PENDING'
    check (backtest_state in ('PENDING','PASS','FAIL')),
  certification_state text not null default 'HOLD_SAMPLE'
    check (certification_state in ('HOLD_SAMPLE','PROPOSED','BACKTEST_PENDING','CERTIFIED','REJECTED')),
  proposed_at timestamptz not null default now(),
  certified_at timestamptz
);

alter table public.contents enable row level security;
alter table public.keywords enable row level security;
alter table public.naver_trend_snapshots enable row level security;
alter table public.search_demand_features enable row level security;
alter table public.gsc_performance_snapshots enable row level security;
alter table public.content_score_snapshots enable row level security;
alter table public.performance_reviews enable row level security;
alter table public.executive_actions enable row level security;
alter table public.winner_patterns enable row level security;
alter table public.weight_certifications enable row level security;
